### ISSUE TITLE
Little issue in the AsNodes() function

### ISSUE THREAD

**Issue by lorico** [marpaia/GonormCypher#1]
Hello,
I realized there is a little issue in the AsNodes function:
This part ::
for _, value := range r.Data[0].([]interface{}) {
        node := new(Node)
        node.Params = value.(map[string]interface{})["data"].(map[string]interface{})
        nodes = append(nodes, node)
    }

Should be replaced by ::
    for _,d := range r.Data{  
        for _, value := range d.([]interface{}) {
            node := new(Node)
            node.Params = value.(map[string]interface{})["data"].(map[string]interface{})
            nodes = append(nodes, node)
        }
    }

=> Otherwise, you always get only 1 node (the first one), even if calling the function "AllNodes".

THANKS ! THIS WRAPPER ID JUST GREAT ! :)

**Comment by marpaia** [comment]
@lorico, good catch. Do you mind submitting a PR with this fix?

**Comment by bramvdbogaerde** [comment]
I added the fix to my own repo, should I send a pull request?

**Comment by marpaia** [comment]
yessss!

**Comment by bramvdbogaerde** [comment]
Could this be closed now?

**Comment by marpaia** [comment]
thanks!
